spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security
    username: root
    password: toor
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
  security:
    user:
      name: user
      password: user
  application:
    name: Jwt-Security
server:
  port: 8081

logging:
  level:
    org.springframework.security: trace